### ISSUE TITLE
Main discussion

### ISSUE THREAD

**Issue by romandragan** [instrumentisto/mol-app-example#1]
@tyranron, ничего, если пользователей будем хранить в Local Storage. С точки зрения безопасности это не ок, но нам сейчас же это и не важно.

**Comment by tyranron** [comment]
@romandragan your REST API server mock is responsible of this. If mock will store users in Local Storage - it is OK.

**Comment by romandragan** [comment]
At this moment application is fully functional and can be reviewed (if needed).

Now I'm trying to implement SSR and Webpack integration in separate branch.

**Comment by tyranron** [comment]
@romandragan it would be nice if you describe it a little bit more in README. That will simplify diving into.

**Comment by romandragan** [comment]
@tyranron, done

**Comment by romandragan** [comment]
**TODO:**
- [ ] SSR (#3)
  - [ ] Develop new routing without hashes `#`
- [ ] Lazy modules loading (webpack) (#2)
- [ ] Dev/Production stages support

**Comment by romandragan** [comment]
@tyranron, does using Gulp is allowed?

**Comment by tyranron** [comment]
@romandragan yup, if you'd like. But why Makefile is required?

**Comment by romandragan** [comment]
@tyranron, for now just asking. I'm thinking of implementing build strategy by using one of: nmp tasks/Makefile/$mol builder.

I've just implemented it using Makefile. Now trying to do the same with npm tasks.

**Comment by tyranron** [comment]
@romandragan the best option is to implement it according to current community best practices. If I understand stuff correctly, it's `npm` tasks right now.

`Makefile`s are meant to be quite rudimentary, and its very uncommon for JS developer to understand them and operate with them. Also, `Makefile`s are not portable for Win platform, so can't be used as convenient way for project dev/build lifecycle.

We usually use `Makefile`s for high-level abstraction of project operations, like `make build`, `make test`, `make release`, etc. And that is intended to be used in continuos delivery pipelines on CI server. But in regular development those commands are not so useful. `Makefile`s are for DevOps'es rather than for Developers. I'm not sure that this example project requires them. Travis CI capabilities are enough to satisfy this project, I suppose.
